# Generated by Django 5.1.2 on 2025-04-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_favorites_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
    ]
