# Generated by Django 5.1.2 on 2025-04-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
